sdm660-common: QCamera2: Include missing head fcntl.h
camera/QCamera2/util/QCameraHALPP.cpp:411:30: error: use of undeclared identifier 'O_RDWR'
    int file_fd = open(name, O_RDWR | O_CREAT, 0777);
                             ^
camera/QCamera2/util/QCameraHALPP.cpp:411:39: error: use of undeclared identifier 'O_CREAT'
    int file_fd = open(name, O_RDWR | O_CREAT, 0777);
                                      ^
2 errors generated.

Signed-off-by: anrui2032 <anrui2032@gmail.com>
Change-Id: Id0ef576cd187ca2e01807b383d51728cb444432d